export const OPEN_SIDE_NAV = 'OPEN_SIDE_NAV';
export const CLOSE_SIDE_NAV = 'CLOSE_SIDE_NAV';

export const GET_ALL_USERS = 'GET_ALL_USERS';

export const GET_ALL_APPOINTEMTNS = 'GET_ALL_APPOINTEMTNS';

export const SAVE_PROFILE = 'SAVE_PROFILE';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_FAILED = 'SAVE_PROFILE_FAILED';